env:
  global:
  - ARTIFACTS_AWS_REGION=eu-west-1
  - ARTIFACTS_S3_BUCKET=rust-ci-artifacts
  - secure: IychfLoM4E7qrFYpDpxc1/dEVlohzLIwqMtyFo52d6rO0aJZTyt5Sq8362lwPpfAaKCGHsTQOc7VjqfEWwh4McXJCe21yGPqdWc39SaDoqPUT5KZ9lQGSzCGN3Y054Md26SoVQkwazD5K8w+EZo8SYKfxGSqI1xaj+nZC/Ddh0o=
  - secure: UwxwaSSJ9KDzLYOweH9aePgv/KOLLFoh4YALdxtaM13VL5v9uXK9gix1DudpuLMMVyw2or00OK8LZOjEhMRmINxmbEDM1s/zfwS/Drx/ygWiy+YIyNBY6GQC0PrmUFjFLuYjanVZOHc2ErowdpHmeYHM7kJcbZqtQDDZqI8xD8o=
before_install:
- yes | sudo add-apt-repository ppa:hansjorg/rust
- sudo apt-get update
install:
- sudo apt-get install rust-nightly
before_script:
- gem install travis-artifacts
script:
- rustpkg build stuff
after_script:
- rustdoc src/stuff/lib.rs
- travis-artifacts upload --path doc --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID
