env:
  global:
  - ARTIFACTS_AWS_REGION=eu-west-1
  - ARTIFACTS_S3_BUCKET=rust-ci-artifacts
  - secure: ToYJCWO7Nflkwla2y96vQx9JamI1CHHr+1PLXJu9WKIw9p2Dz1ldEhhfKKnBNk3Cs9k2+dp0dy5HfLRPfyiruLpM/SbTU4GSN1oQoo5O1WDNYsmMHxoFgv/IAE12PbYaqR9F/iTLJYrEvqkaINFIXycnjiqDvrG69+fuiKmK58g=
  - secure: EuH5gXyKCyKm15alN/rBmVfkYELl4b3axN81Trb38hjyrEXZjh+hTnkg8kZdojqo6gIgZw3NJwK6mnGUnqwMC462pSjY27Xx4/o929osZ4D+FyyTGPT/DOSxQZCXFg4U0n8YzLDIqwkb4rq36fND+Esx51eZBwP+hKbzBMTiqMY=
before_install:
- yes | sudo add-apt-repository ppa:hansjorg/rust
- sudo apt-get update
install:
- sudo apt-get install rust-nightly
before_script:
- gem install travis-artifacts
script:
- rustpkg build stuff
after_script:
- rustdoc src/stuff/lib.rs
- ls -lR doc
- travis-artifacts upload --path doc --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID
