env:
  global:
    - secure: PuBNquOB5iyIcGMmK9us2YG4lYvVKDfeYqGVNyFgxLD2J8z7HxOB0O5+ICXEjqp7Nprtepe4urBrAQi9l3XGUpnGi3Gln1Fji3s+A/E+vb4NbA6DWjbNVi1mzfTmeUOWAHDnIS12ncBXykAwnPEc4RGDlOpTT41/rMjMXhbqym8=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - rustpkg build stuff
  - rustdoc src/stuff/lib.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
