env:
  global:
  - secure: Y3pfth0oJ6Of9q8Sgrba/q2O8xycMdz5psbNbtOHMjdgaWFHyIQp63tjU+LBp8vxTA4VmSYZUjf7EH2euL7AMZC7Q9pKZKOOa+VepeGvMvt+FviY3t2kCxR5X7b4ymxhqNVjnLAD3AdU9Zz2Q4YIg0+VUgGA53SO0AGUJc6UMPI=
  - USIKKER=hepp
  - secure: raS5BUIOz48UFjhmdjlNttD7va7gl2wV0tW1DHR861QBVI99RPboYyT8phw0t1+ks6OAGa0Z/zCk1cmP5pVJBjuNkpQG2bBZdSzZKJewcMg3oqT5s4z2cQWfw88C8kBVACNu4DVi8CbMiIsIcO2loSKkiqQW2ICnz2zOlI1N4Ww=
before_install:
- yes | sudo add-apt-repository ppa:hansjorg/rust
- sudo apt-get update
install:
- sudo apt-get install rust-nightly
script:
- rustpkg build stuff
- echo $HEIHEI
- echo $USIKKER
- echo $TJO
