env:
  global:
  - ARTIFACTS_AWS_REGION=eu-west-1
  - ARTIFACTS_S3_BUCKET=rust-ci-artifacts
  - secure: IychfLoM4E7qrFYpDpxc1/dEVlohzLIwqMtyFo52d6rO0aJZTyt5Sq8362lwPpfAaKCGHsTQOc7VjqfEWwh4McXJCe21yGPqdWc39SaDoqPUT5KZ9lQGSzCGN3Y054Md26SoVQkwazD5K8w+EZo8SYKfxGSqI1xaj+nZC/Ddh0o=
  - secure: UwxwaSSJ9KDzLYOweH9aePgv/KOLLFoh4YALdxtaM13VL5v9uXK9gix1DudpuLMMVyw2or00OK8LZOjEhMRmINxmbEDM1s/zfwS/Drx/ygWiy+YIyNBY6GQC0PrmUFjFLuYjanVZOHc2ErowdpHmeYHM7kJcbZqtQDDZqI8xD8o=
  - secure: MdG1dwSfJZHmrdL7Vv9/sg636OXtsZm4fREtS6e25jsAJQBtofcZlpkM3cIqX5mLmJ0b4QutECdFeWEc6llElAxXlSAxdW7nDOwOxgSXMu9IpKvhtOCNnLaiPRqUDajCe13gWLlPXbz8k7SJKEc6Zr8q+PTB7b6xLDk5GuiB6v4=
script:
- echo "test"
after_script:
- echo $HIDDEN
